// <auto-generated />
using System;
using AcAuthNetSample.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcAuthNetSample.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228012238_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.TokenAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasComment("登录平台，Android、IOS、Windows等");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("建立人");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime2")
                        .HasComment("登录过期时间");

                    b.Property<int>("FailCount")
                        .HasColumnType("int")
                        .HasComment("失败次数");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasComment("登录IP");

                    b.Property<DateTime>("LoginOn")
                        .HasColumnType("datetime2")
                        .HasComment("登录时间");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(max)")
                        .HasComment("RefreshToken");

                    b.Property<string>("Token")
                        .HasColumnType("varchar(max)")
                        .HasComment("Token");

                    b.Property<DateTime>("UpdateOn")
                        .HasColumnType("datetime2")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("修改人");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasComment("登录设备");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("access_token");
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avator")
                        .HasColumnType("varchar(64)")
                        .HasComment("头像");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasComment("建立人");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasComment("描述");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(32)")
                        .HasComment("邮箱");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(15)")
                        .HasComment("手机号");

                    b.Property<string>("Salt")
                        .HasColumnType("varchar(32)")
                        .HasComment("密钥的盐");

                    b.Property<DateTime>("UpdateOn")
                        .HasColumnType("datetime2")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasComment("修改人");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.TokenAccess", b =>
                {
                    b.HasOne("AcAuthNetSample.Core.Domain.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
