// <auto-generated />
using System;
using AcAuthNetSample.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcAuthNetSample.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101110620_修改Time数据类型")]
    partial class 修改Time数据类型
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("component")
                        .HasColumnOrder(5)
                        .HasComment("前端组件路径（Vue/React组件地址，菜单类型为2时必填）");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("create_on")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id")
                        .HasComment("建立人");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icon")
                        .HasColumnOrder(9)
                        .HasComment("菜单图标（如el-icon-user）");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled")
                        .HasColumnOrder(8)
                        .HasComment("是否启用（true=启用，false=禁用）");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit")
                        .HasColumnName("is_external")
                        .HasColumnOrder(10)
                        .HasComment("是否外链（true=是，false=否）");

                    b.Property<bool>("IsHide")
                        .HasColumnType("bit")
                        .HasColumnName("is_hide")
                        .HasColumnOrder(11)
                        .HasComment("是否隐藏菜单（true=隐藏，false=显示）");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("menu_name")
                        .HasColumnOrder(2)
                        .HasComment("菜单名称（显示用）");

                    b.Property<string>("MenuType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("menu_type")
                        .HasColumnOrder(3)
                        .HasComment("菜单类型（1=目录，2=菜单，3=按钮）");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id")
                        .HasColumnOrder(1)
                        .HasComment("父菜单ID（顶级菜单填0）");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("path")
                        .HasColumnOrder(4)
                        .HasComment("前端路由路径（菜单类型为2时必填）");

                    b.Property<string>("Permission")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("permission")
                        .HasColumnOrder(6)
                        .HasComment("权限标识（按钮类型必填，格式：模块:功能:操作）");

                    b.Property<string>("Redirect")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("redirect")
                        .HasColumnOrder(12)
                        .HasComment("路由重定向地址（目录类型常用）");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remark")
                        .HasColumnOrder(13)
                        .HasComment("菜单备注/说明");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasColumnOrder(7)
                        .HasComment("排序号（数字越小越靠前）");

                    b.Property<DateTimeOffset>("UpdateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("update_on")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id")
                        .HasComment("修改人");

                    b.HasKey("Id");

                    b.ToTable("menu", t =>
                        {
                            t.HasComment("系统菜单表（含目录、菜单、按钮权限）");
                        });
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("create_on")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id")
                        .HasComment("建立人");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description")
                        .HasColumnOrder(3)
                        .HasComment("角色描述/备注（说明角色用途）");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled")
                        .HasColumnOrder(5)
                        .HasComment("是否启用（禁用后角色关联的权限失效）");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system")
                        .HasColumnOrder(4)
                        .HasComment("是否系统内置角色（内置角色不可删除/修改编码）");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_code")
                        .HasColumnOrder(2)
                        .HasComment("角色编码（全局唯一，用于权限校验）");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name")
                        .HasColumnOrder(1)
                        .HasComment("角色名称（如超级管理员、普通用户）");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasColumnOrder(6)
                        .HasComment("排序号（数字越小越靠前）");

                    b.Property<DateTimeOffset>("UpdateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("update_on")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id")
                        .HasComment("修改人");

                    b.HasKey("Id");

                    b.ToTable("role", t =>
                        {
                            t.HasComment("系统角色表（用于权限分配）");
                        });
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("create_on")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id")
                        .HasComment("建立人");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id")
                        .HasColumnOrder(2)
                        .HasComment("菜单ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id")
                        .HasColumnOrder(1)
                        .HasComment("角色ID");

                    b.Property<DateTimeOffset>("UpdateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("update_on")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id")
                        .HasComment("修改人");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_menu", t =>
                        {
                            t.HasComment("角色菜单关联表（多对多）");
                        });
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.TokenAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("client")
                        .HasComment("登录平台，Android、IOS、Windows等");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("create_on")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id")
                        .HasComment("建立人");

                    b.Property<DateTimeOffset>("ExpireTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expire_time")
                        .HasComment("登录过期时间");

                    b.Property<int>("FailCount")
                        .HasColumnType("int")
                        .HasColumnName("fail_count")
                        .HasComment("失败次数");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ip")
                        .HasComment("登录IP");

                    b.Property<DateTimeOffset>("LoginOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("login_on")
                        .HasComment("登录时间");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("refresh_token")
                        .HasComment("RefreshToken");

                    b.Property<string>("Token")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("token")
                        .HasComment("Token");

                    b.Property<DateTimeOffset>("UpdateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("update_on")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id")
                        .HasComment("修改人");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("user_agent")
                        .HasComment("登录设备");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("access_token");
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avator")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("avator")
                        .HasComment("头像");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("create_on")
                        .HasComment("创建时间");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id")
                        .HasComment("建立人");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description")
                        .HasComment("描述");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("nick_name")
                        .HasComment("昵称");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone")
                        .HasComment("手机号");

                    b.Property<string>("Salt")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("salt")
                        .HasComment("密钥的盐");

                    b.Property<DateTimeOffset>("UpdateOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("update_on")
                        .HasComment("修改时间");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id")
                        .HasComment("修改人");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.RoleMenu", b =>
                {
                    b.HasOne("AcAuthNetSample.Core.Domain.Auth.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcAuthNetSample.Core.Domain.Auth.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AcAuthNetSample.Core.Domain.Auth.Entities.TokenAccess", b =>
                {
                    b.HasOne("AcAuthNetSample.Core.Domain.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
